/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorioprogramacao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronaldo
 */
public class AddBncoDeDados extends javax.swing.JFrame {

    /**
     * Creates new form AddBncoDeDados
     */
    public AddBncoDeDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEcluir = new javax.swing.JButton();
        btxEditar = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PRODUTOS");

        jLabel2.setText("CODIGO");

        jLabel3.setText("NOME:");

        jLabel4.setText("PREÇO:");

        jLabel5.setText("QUA TIDADE:");

        TxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoActionPerformed(evt);
            }
        });

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEcluir.setText("Excluir");
        btnEcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcluirActionPerformed(evt);
            }
        });

        btxEditar.setText("Editar");
        btxEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxEditarActionPerformed(evt);
            }
        });

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btxEditar)
                        .addGap(29, 29, 29)
                        .addComponent(btnConsulta)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEcluir)
                    .addComponent(btxEditar)
                    .addComponent(btnConsulta))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int codigo = Integer.parseInt(TxtCodigo.getText());
        String nome = txtNome.getText();
        double preco = Double.parseDouble(txtPreco.getText());
        int quantidade = Integer.parseInt(txtQuantidade.getText());

        // define SQL
        String SQL = "insert produto values(?,?,?,?)";

        // define o usuario banco de dados
        String url = "jdbc:mysql://127.0.0.1:3306/fio";
        String usuario = "root";
        String senha = "root";

        try {
            //conecat ao banco de dados
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            // preparar o comando que sera executado
            PreparedStatement comando = conexao.prepareStatement(SQL);

            //define o valor de cada interrogação
            comando.setInt(1, codigo);
            comando.setString(2, nome);
            comando.setDouble(3, preco);
            comando.setInt(4, quantidade);

            //executar o camando
            comando.executeUpdate();

            //liberar recurso
            comando.close();
            conexao.close();

            // exibir uma mensagem de sucesso
            JOptionPane.showMessageDialog(null, "Inseridos com sucesso!!!");

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao salval!!!");
            erro.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcluirActionPerformed
        // evento do botão excluir

        int codigo = Integer.parseInt(TxtCodigo.getText());
        // Definição dos banco de dados
        String url = "jdbc:mysql://127.0.0.1:3306/fio";
        String usuario = "root";
        String senha = "root";

        // definição da sql
        String sql = "DELETE FROM PRODUTO WHERE CODIGO = ?";

        try {
            //capitura uma conexão
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            // criar um comando
            PreparedStatement comando = conexao.prepareStatement(sql);

            // substituir as interrogações
            comando.setInt(1, codigo);

            // executa o comando
            comando.executeUpdate();

            // libere recurso
            comando.close();
            conexao.close();

            JOptionPane.showMessageDialog(null, "excluido com exito!!!");
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir!!!");
            erro.printStackTrace();
        }

    }//GEN-LAST:event_btnEcluirActionPerformed

    private void btxEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxEditarActionPerformed

        // capituara dados
        int codigo = Integer.parseInt(TxtCodigo.getText());
        String nome = txtNome.getText();
        double preco = Double.parseDouble(txtPreco.getText());
        int quantidade = Integer.parseInt(txtQuantidade.getText());

        // Definição dos banco de dados
        String url = "jdbc:mysql://127.0.0.1:3306/fio";
        String usuario = "root";
        String senha = "root";

        // definição da sql
        String sql = "UPDATE PRODUTO SET NOME = ?, PRECO = ?, QUANTIDADE= ? WHERE CODIGO = ?";

        try {
            //capitura uma conexão
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            // criar um comando
            PreparedStatement comando = conexao.prepareStatement(sql);

            // substituir as interrogações
            comando.setString(1, nome);
            comando.setDouble(2, preco);
            comando.setInt(3, quantidade);
            comando.setInt(4, codigo);

            // executa o comando
            comando.executeUpdate();

            // libere recurso
            comando.close();
            conexao.close();

            JOptionPane.showMessageDialog(null, "alterado com exito!!!");
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar!!!");
            erro.printStackTrace();
        }

    }//GEN-LAST:event_btxEditarActionPerformed

    private void TxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed

        int codigo = Integer.parseInt(TxtCodigo.getText());

        // Definição dos banco de dados
        String url = "jdbc:mysql://127.0.0.1:3306/fio";
        String usuario = "root";
        String senha = "root";

        // definição da sql
        String sql = "SELECT * FROM PRODUTO WHERE CODIGO=?";

        try {
            //capitura uma conexão
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            // criar um comando
            PreparedStatement comando = conexao.prepareStatement(sql);

            // substituir as interrogações
            comando.setInt(1, codigo);

            //captura o redultado da consulta
            ResultSet resultado = comando.executeQuery();

            // verifica se retornou algo
            /*if (resultado.next() == true) {
                // extrai os dados
                String nome = resultado.getString("nome");
                Double preco = resultado.getDouble("preco");
                int quantidade = resultado.getInt("quantidade");
                JOptionPane.showMessageDialog(null, "\ncodigo: " + codigo + "\n nome: " + nome + "\npreço: "
                        + preco + "\nQuantidade:" + quantidade);
            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
            }*/
            DefaultTableModel modelo = (DefaultTableModel) tblProduto.getModel();
            while (resultado.next()){
                int codigoRec = resultado.getInt("codigo");
                String nome = resultado.getString("nome");
                Double preco = resultado.getDouble("preco");
                int quantidade = resultado.getInt("quantidade");
                
                Object[] linha = new Object[4];
                
                linha[0] = codigo;
                linha[1] = nome;
                linha[2] = preco;
                linha[3] = quantidade;
                
                modelo.addRow(linha);
                
                
            }

            // libere recurso
            comando.close();
            conexao.close();

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar!!!");
            erro.printStackTrace();
        }


    }//GEN-LAST:event_btnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBncoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBncoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBncoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBncoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBncoDeDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btxEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
