/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorioprogramacao;

/**
 *
 * @author Ronaldo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnBar = new javax.swing.JMenuBar();
        mmArquivo = new javax.swing.JMenu();
        mnitenSair = new javax.swing.JMenuItem();
        mmCadastro = new javax.swing.JMenu();
        mnitemProdutos = new javax.swing.JMenuItem();
        mmEstados = new javax.swing.JMenuItem();
        mmCidades = new javax.swing.JMenuItem();
        mmMovim = new javax.swing.JMenu();
        immEntrada = new javax.swing.JMenuItem();
        immSaidas = new javax.swing.JMenuItem();
        mmRelatorio = new javax.swing.JMenu();
        immRelProdMaisVend = new javax.swing.JMenuItem();
        mmAjuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mmArquivo.setText("Arquivo");

        mnitenSair.setText("Sair");
        mnitenSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitenSairActionPerformed(evt);
            }
        });
        mmArquivo.add(mnitenSair);

        mnBar.add(mmArquivo);

        mmCadastro.setText("Cadastro");

        mnitemProdutos.setText("Produtos");
        mnitemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemProdutosActionPerformed(evt);
            }
        });
        mmCadastro.add(mnitemProdutos);

        mmEstados.setText("Estados");
        mmEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmEstadosActionPerformed(evt);
            }
        });
        mmCadastro.add(mmEstados);

        mmCidades.setText("cidades");
        mmCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmCidadesActionPerformed(evt);
            }
        });
        mmCadastro.add(mmCidades);

        mnBar.add(mmCadastro);

        mmMovim.setText("Movimentações");

        immEntrada.setText("Entradas");
        mmMovim.add(immEntrada);

        immSaidas.setText("Saidas");
        mmMovim.add(immSaidas);

        mnBar.add(mmMovim);

        mmRelatorio.setText("Relatório");

        immRelProdMaisVend.setText("Produtos Mais Vandidos");
        mmRelatorio.add(immRelProdMaisVend);

        mnBar.add(mmRelatorio);

        mmAjuda.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mmAjuda.add(jMenuItem3);

        mnBar.add(mmAjuda);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemProdutosActionPerformed
        Produtos tela = new Produtos();
        tela.setVisible(true);
    }//GEN-LAST:event_mnitemProdutosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mmEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmEstadosActionPerformed
       Estados tela = new Estados();
       tela.setVisible(true);
    }//GEN-LAST:event_mmEstadosActionPerformed

    private void mmCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmCidadesActionPerformed
       Cidades tela = new Cidades();
       tela.setVisible(true);
    }//GEN-LAST:event_mmCidadesActionPerformed

    private void mnitenSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitenSairActionPerformed
        dispose();
    }//GEN-LAST:event_mnitenSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem immEntrada;
    private javax.swing.JMenuItem immRelProdMaisVend;
    private javax.swing.JMenuItem immSaidas;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mmAjuda;
    private javax.swing.JMenu mmArquivo;
    private javax.swing.JMenu mmCadastro;
    private javax.swing.JMenuItem mmCidades;
    private javax.swing.JMenuItem mmEstados;
    private javax.swing.JMenu mmMovim;
    private javax.swing.JMenu mmRelatorio;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenuItem mnitemProdutos;
    private javax.swing.JMenuItem mnitenSair;
    // End of variables declaration//GEN-END:variables
}
